#!/bin/bash

sm2 -start DATASTREAM THIRD_PARTY_APPLICATION API_DEFINITION API_SUBSCRIPTION_FIELDS THIRD_PARTY_DEVELOPER PUSH_PULL_NOTIFICATIONS_API API_PLATFORM_MICROSERVICE DATASTREAM
sm2 -start INTEGRATION_CATALOGUE_ADMIN_API INTEGRATION_CATALOGUE

./run_local.sh
